language: node_js
node_js:
- node
dist: trusty
sudo: false
install:
- npm ci
before_deploy:
- npm run build-client
- rm -rf node_modules
deploy:
  skip_cleanup: true
  provider: heroku
  app: amexswapi
  api_key: 
  secure: XqJDRAgRgyB1UvjS5TgH+vs9dl//i1a5jcG4MPglkMlk+PtagQgR04jq72SBh0dxH0gYmMdCLESP4Kq5qaAFw3EtS54sydL/3CHaHS+auwp+sAuUKZGlsTadG17bVz8RTfoJaFnX5Am3nG+ZuqwpREtLgy/yi0AI/Xu+lBHxXHx5PJ/tyR5EcKq8NmeK6JPcswsItF3Bo4Ptv/9vBf6ggDwRqiGpsQI5OrqoNOUpaIpIGUDiYAoipLAkbgpwQ73GxtCsYG1XbmvYF5FY2igORFH+4sp25VsQZBV7X+sdBenyPhJWDtKj2s+xYH7oC14V2/VWbm1j2FUO6Af4r95dRHFGCfwsQOBsjqDLwRh8h61TXb8b0UbHpdRsufQcnCdl4+ZacUMoJLsk6savtwxoXe2ZKleHN/dzfH6RznucUCcTVzVKml99y+I/FA4Q7HAvitRL5KNAvS0WQgoOR0We9SqpqSao2E57u9Pk5C2tJ5LnLdIp2plkBExM+rXcbSEyFJ9cq5QBpM/Odc4WaCJR/zv32PX8ZWNtpWI7rlvej5xGihkM/s6fVlF9cy5Z1WFyD7zTcLMiZhAVmSkYVUPhn/bS0Ga+sW03dOnr9vrje5D509ywHrZiY40u+YsZD5cNGMr2stcJMJr8feqIaq1g+IfBMdCugcVOTCOSTqTRVOs=
env:
  global:
    secure: ebBoA9QWtmdqgUCmmu4iDQ5uzfeeEBzes+zUKeX/7MKVnxk+wrMus87WVEzp+38LirYLUGaX9iVaLvyml1SYSXcqFR7mYKE8riJObBlyE8XFfOckQi6bzwZIToBsQrm8KhNllDvi03JAdGY/H3JzEIez+SF3F8tSZOZ8Ux3DM5Af8c8ZpQDGrINdiBAVL9n10OsPyr2XuZAf20msTwICX0QJPBNIVEkhqRX2h5SzilLrHNCKrivZ+MnXaFf3MYREqpKwEEW0LKcN83UqnU0gRdH9oXOaB/37jixMUUzRlcBt4BDnRrDvCA9U3rnK83U5m9O9bBmG6Sul8XZFuP0wmly4Q4TdK/amUx8pIc+vtgrlIvQp3RBCMvubC4inriAnMh/C+EuYarEatbJsMK0LxF/rsgnm8NIk/GtHOEvSdpAO6zRu033Aw9UGs25gSbfVKQ+33ugub383iL4NmgUpP6q2EL4keR9m5qRcB0PWksInDBNbHLGicWX64kq981p4Isbhx0enVdvFNWe21VtbRRnu3p1uF0KVrGYknQrUAya6mEuMb72/AnjWz0hHlEmTdcQOfmltoSQi0umIyDyWAjm2dRBQUfWBJocIfCsB5b0Uaew4WyJEEWLHgg4r97W5I5yLDPDwA+b1KJhpJ52YyYNmKlM47MaiyGg5nBECt+I=
